version: '3.7'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 10s
      interval: 1s
      retries: 10

  web:
    depends_on:
      db:
        condition: service_healthy

    image: priest4612/yamdb_final:latest
    restart: always
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static/
      - ./media:/var/www/media/
    depends_on:
      - web
