# Generated by Django 2.2.16 on 2021-09-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210920_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='score',
        ),
    ]
